global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /opt/ssl/certs
	crt-base /opt/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers  ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options  no-sslv3
	ssl-server-verify         none
	tune.ssl.default-dh-param 2048

defaults
	log	global
	mode	tcp
	option	tcplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

listen stats
	bind 0.0.0.0:8090
	mode http
	stats enable
	stats refresh 10s
	stats show-node
	stats auth haproxy:passw0rd
	stats uri /haproxy/stats

frontend https-in
	bind *:8443     ssl crt my-crt-key.pem
	default_backend app

backend app
	balance roundrobin
	option  httpchk GET /healthz
  http-check expect rstatus (2|3)[0-9][0-9]
	option  log-health-checks
	server  myweb1 myweb1:443 check ssl crt my-crt-key.pem inter 10s fall 3 rise 2
	server  myweb2 myweb2:443 check ssl crt my-crt-key.pem inter 10s fall 3 rise 2
